# Generated by Django 3.0.4 on 2020-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemodel',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='icon_url',
            field=models.CharField(default=31, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timemodel',
            name='status',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timemodel',
            name='tmp_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='tmp_max',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timemodel',
            name='tmp_min',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
