# Generated by Django 3.0.4 on 2020-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200322_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='tmp_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='tmp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='tmp_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
